<?php
/**
 * ListingImageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Etsy Open API v3
 *
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2023 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.
 *
 * OpenAPI spec version: 3.0.0
 * Contact: developers@etsy.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.42
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ListingImageTest Class Doc Comment
 *
 * @category    Class
 * @description Reference urls and metadata for an image associated with a specific listing. The &#x60;url_fullxfull&#x60; parameter contains the URL for full-sized binary image file.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ListingImageTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListingImage"
     */
    public function testListingImage()
    {
    }

    /**
     * Test attribute "listing_id"
     */
    public function testPropertyListingId()
    {
    }

    /**
     * Test attribute "listing_image_id"
     */
    public function testPropertyListingImageId()
    {
    }

    /**
     * Test attribute "hex_code"
     */
    public function testPropertyHexCode()
    {
    }

    /**
     * Test attribute "red"
     */
    public function testPropertyRed()
    {
    }

    /**
     * Test attribute "green"
     */
    public function testPropertyGreen()
    {
    }

    /**
     * Test attribute "blue"
     */
    public function testPropertyBlue()
    {
    }

    /**
     * Test attribute "hue"
     */
    public function testPropertyHue()
    {
    }

    /**
     * Test attribute "saturation"
     */
    public function testPropertySaturation()
    {
    }

    /**
     * Test attribute "brightness"
     */
    public function testPropertyBrightness()
    {
    }

    /**
     * Test attribute "is_black_and_white"
     */
    public function testPropertyIsBlackAndWhite()
    {
    }

    /**
     * Test attribute "creation_tsz"
     */
    public function testPropertyCreationTsz()
    {
    }

    /**
     * Test attribute "created_timestamp"
     */
    public function testPropertyCreatedTimestamp()
    {
    }

    /**
     * Test attribute "rank"
     */
    public function testPropertyRank()
    {
    }

    /**
     * Test attribute "url_75x75"
     */
    public function testPropertyUrl75x75()
    {
    }

    /**
     * Test attribute "url_170x135"
     */
    public function testPropertyUrl170x135()
    {
    }

    /**
     * Test attribute "url_570x_n"
     */
    public function testPropertyUrl570xN()
    {
    }

    /**
     * Test attribute "url_fullxfull"
     */
    public function testPropertyUrlFullxfull()
    {
    }

    /**
     * Test attribute "full_height"
     */
    public function testPropertyFullHeight()
    {
    }

    /**
     * Test attribute "full_width"
     */
    public function testPropertyFullWidth()
    {
    }

    /**
     * Test attribute "alt_text"
     */
    public function testPropertyAltText()
    {
    }
}
