<?php
/**
 * ShopShippingProfileTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Etsy Open API v3
 *
 * <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2023 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.
 *
 * OpenAPI spec version: 3.0.0
 * Contact: developers@etsy.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.42
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ShopShippingProfileTest Class Doc Comment
 *
 * @category    Class
 * @description Represents a profile used to set a listing&#x27;s shipping information. Please note that it&#x27;s not possible to create calculated shipping templates via the API. However, you can associate calculated shipping profiles created from Shop Manager with listings using the API.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShopShippingProfileTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ShopShippingProfile"
     */
    public function testShopShippingProfile()
    {
    }

    /**
     * Test attribute "shipping_profile_id"
     */
    public function testPropertyShippingProfileId()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "min_processing_days"
     */
    public function testPropertyMinProcessingDays()
    {
    }

    /**
     * Test attribute "max_processing_days"
     */
    public function testPropertyMaxProcessingDays()
    {
    }

    /**
     * Test attribute "processing_days_display_label"
     */
    public function testPropertyProcessingDaysDisplayLabel()
    {
    }

    /**
     * Test attribute "origin_country_iso"
     */
    public function testPropertyOriginCountryIso()
    {
    }

    /**
     * Test attribute "is_deleted"
     */
    public function testPropertyIsDeleted()
    {
    }

    /**
     * Test attribute "shipping_profile_destinations"
     */
    public function testPropertyShippingProfileDestinations()
    {
    }

    /**
     * Test attribute "shipping_profile_upgrades"
     */
    public function testPropertyShippingProfileUpgrades()
    {
    }

    /**
     * Test attribute "origin_postal_code"
     */
    public function testPropertyOriginPostalCode()
    {
    }

    /**
     * Test attribute "profile_type"
     */
    public function testPropertyProfileType()
    {
    }

    /**
     * Test attribute "domestic_handling_fee"
     */
    public function testPropertyDomesticHandlingFee()
    {
    }

    /**
     * Test attribute "international_handling_fee"
     */
    public function testPropertyInternationalHandlingFee()
    {
    }
}
